const userTypes = {
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
  SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
  SIGN_UP_USER_START: 'SIGN_UP_USER_START',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  USER_CHECK_FLAG: "USER_CHECK_FLAG",
  ADD_USER_ADDRESS_START: "ADD_USER_ADDRESS_START",
  ADD_ADDRESS_MODAL_FLAG: "ADD_ADDRESS_MODAL_FLAG",
  ADD_USER_ADDRESS_FLAG: "ADD_USER_ADDRESS_FLAG"
};

export default userTypes;